source :rubygems
gem 'sinatra', '1.3.0'
gem 'sinatra-contrib'
gem 'thin'
gem 'haml'
gem 'tilt'
gem 'couchrest'
gem 'json'
gem 'uuid'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
