ruby "2.0.0"
source 'https://rubygems.org'
gem 'sinatra', '>= 1.3.3'
gem 'thin'
gem 'haml'
gem 'couchrest'
gem 'json'
gem 'uuid'
gem 'rack-cors'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-yahoo'
